merge_queue:
  mode: parallel
  max_parallel_checks: 2
scopes:
  source:
    manual:
queue_rules:
  - name: default
    queue_conditions: []
    merge_conditions:
      - check-success = vm4-all-scopes-never
    batch_size: 1
