merge_queue:
  max_parallel_checks: 10

queue_rules:
  - name: default
    queue_conditions:
      - author = livastic-vm4-secondary-20260911
    merge_conditions:
      - check-success = VM4 calibration
    merge_method: merge
    checks_timeout: auto
    autoqueue: true
